augment: true
batch: 32
bbox_interval: -1
cache: false
class_weights: true
close_mosaic: 10
conf: 0.001
copy_paste: 0.0
cos_lr: true
data: dataset/data_augmented.yaml
degrees: 10.0
device: 0
epochs: 100
exist_ok: true
export:
  dynamic: true
  format: onnx
fliplr: 0.5
flipud: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
iou: 0.6
label_smoothing: 0.1
loss: cross_entropy
lr0: 0.01
lrf: 0.1
mixup: 0.1
model: yolov8s.pt
momentum: 0.937
mosiac: 1.0
name: stage1_training
overlap_mask: true
patience: 50
perspective: 0.0
plots: true
project: mangrove_detection
save_hybrid: false
save_json: true
save_period: -1
scale: 0.5
shear: 0.0
single_cls: false
time: None
translate: 0.1
val: true
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
