batch: 32
box: 7.5
cls: 0.5
data: dataset/data_augmented.yaml
device: cpu
dfl: 1.5
epochs: 200
exist_ok: true
imgsz: 640
label_smoothing: 0.1
lr0: 0.01
lrf: 0.1
model: yolov8s.pt
momentum: 0.937
name: augmented_training
patience: 50
project: runs/train
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
